"use client";

import { createContext, useContext, useEffect, useMemo, useSyncExternalStore } from "react";
import type { ReactNode } from "react";

export type StorefrontLanguage = "en" | "vi";
export type TranslationValues = Record<string, string | number>;

type LanguageContextValue = {
  language: StorefrontLanguage;
  setLanguage: (language: StorefrontLanguage) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey, values?: TranslationValues) => string;
};

const STORAGE_KEY = "starliar-language";
const LANGUAGE_CHANGE_EVENT = "starliar-language-change";

export const translations = {
  en: {
    account: "Account",
    accountExists: "This email already has an account. Sign in instead.",
    accountPrompt: "Sign in to save favorites and see your orders.",
    accountNumber: "Account",
    addFavorite: "Add {product} to favorites",
    addToCart: "Add to cart",
    addedToCart: "{product} added to cart",
    all: "All",
    bags: "Bags",
    bank: "Bank",
    buyNow: "Buy now",
    buyNowCheckout: "Buy now checkout",
    calculatedAtCheckout: "Calculated at checkout",
    campaign: "Campaign",
    campaignTitle: "After dark uniform",
    care: "Care",
    careDescription: "Cold gentle wash, dry flat, and avoid direct heat to preserve the garment surface.",
    cart: "Cart",
    cartEmpty: "Your cart is empty.",
    cartEmptyDescription: "Add products from the shop to continue to checkout.",
    cartItemCount: "{count} item",
    cartItemCountPlural: "{count} items",
    cartWithCount: "Cart, {count} items",
    categoryBags: "Bags",
    categoryShirt: "Shirt",
    categoryShorts: "Shorts",
    categoryTshirt: "T-Shirt",
    closeSearch: "Close search",
    close: "Close",
    closePaymentNotification: "Close payment notification",
    collectionNotes: "Collection notes",
    contact: "Contact",
    continueShopping: "Continue shopping",
    continueWithGoogle: "Continue with Google",
    country: "Country",
    creatingPayment: "Creating payment...",
    customerCare: "Customer care",
    delivery: "Delivery",
    details: "Details",
    deliveryAddress: "Delivery address",
    deliveryLocation: "Delivery location",
    deliveryNote: "Delivery note",
    deliveryPin: "Delivery pin",
    deliveryPinDescription: "Click the map or use your current location.",
    discover: "Discover",
    discoverBagsAlt: "Starlier tote bag carried at night",
    discoverShirtsAlt: "Starlier shirt in an interior setting",
    emptyProducts: "No products are visible yet.",
    enterShop: "Enter the shop",
    estimatedShipping: "Estimated shipping",
    exchangeReturns: "Exchange and returns",
    exploreCategory: "Explore {category}",
    firstSignal: "First Signal",
    fit: "Fit",
    fitDescription: "Relaxed volume with clean shoulders, cropped layers, and utility lines.",
    fitStructured: "Structured unisex silhouette",
    fullName: "Full name",
    footerContact: "Contact",
    footerEmail: "care@starlier.com",
    footerHours: "Mon-Sat, 10:00-19:00",
    footerLocation: "Hanoi, Vietnam",
    footerNote: "Quiet streetwear silhouettes, prepared for the first signal after midnight.",
    footerPolicies: "Policies",
    footerSocial: "Social",
    footerTagline: "Cinematic unisex fashion from Hanoi.",
    email: "Email",
    emailUsedAtCheckout: "Email used at checkout",
    favorites: "Favorites",
    findGuestOrders: "Find guest orders",
    findOrderHistory: "Find your order history",
    languageEnglish: "English",
    languageVietnamese: "Tiếng Việt",
    itemCount: "{count} items",
    latitude: "Latitude",
    latestRelease: "Latest release",
    material: "Material",
    materialDescription: "Poplin, mesh, and compact fleece balanced for sharp everyday wear.",
    memo: "Memo",
    newArrival: "New arrival",
    noCheckoutItems: "No checkout item found. Add a product again before payment.",
    newsletter: "Newsletter",
    newsletterCopy: "Receive drops, restocks, and private campaign notes.",
    paymentSecurity: "Secure payment",
    palette: "Palette",
    paletteDescription: "Paper, ink, frost gray, and small cold-blue signals.",
    payByQr: "Pay by QR",
    payment: "Payment",
    paymentConfirmed: "Payment confirmed",
    paymentResultDescription: "Your payment is being confirmed. Starlier updates the order from the payment provider callback.",
    paymentStatus: "Payment status",
    paymentSuccessDescription: "Your order has been confirmed. Starlier will prepare it and contact you if needed.",
    paymentSuccessful: "Payment successful",
    lowStock: "Low stock: {count} left",
    pieceAvailable: "1 piece available",
    piecesAvailable: "{count} pieces available",
    soldOut: "Sold out",
    phone: "Phone",
    postalCode: "Postal code",
    province: "Province / state",
    privacy: "Privacy",
    primaryNavigation: "Primary navigation",
    productCategories: "Product categories",
    productDetails: "Product service details",
    productFromCollection: "{category} from {collection} with a clean everyday finish.",
    productGallery: "{product} imagery",
    qrAlt: "SePay QR for order {orderNumber}",
    qrExpired: "QR expired",
    qrExpiredDescription: "Create the order again to receive a new QR code before transferring.",
    qrExpiredTitle: "The QR code expired after 5 minutes.",
    qrRemaining: "{time} remaining",
    qrValidFor: "QR valid for {time}",
    recentlyViewed: "RECENTLY VIEWED",
    removeFavorite: "Remove {product} from favorites",
    removeRecentlyViewed: "Remove recently viewed products",
    remove: "REMOVE",
    resultCount: "{count} results",
    returns: "Returns",
    returnToShop: "Return to shop",
    scanToPay: "Scan to pay",
    search: "Search",
    searchDialog: "Search products",
    searchEmpty: "No exact match yet. Try product names, categories, collection names, or material words.",
    searchPlaceholder: "Please enter the search term(s)",
    searchResults: "SEARCH RESULTS",
    searchTrends: "SEARCH TRENDS",
    searching: "Searching...",
    sepayInstruction: "Keep the amount and memo unchanged so SePay can confirm the payment automatically.",
    shirts: "Shirts",
    shipping: "Shipping",
    shippingAtCheckout: "Vietnam delivery prepared at checkout",
    shippingReturns: "Shipping & returns",
    shippingReturnsDescription: "Orders are prepared after payment confirmation. Return support is available for unworn items.",
    shop: "All products",
    shopAll: "View all",
    shopBreadcrumb: "Shop breadcrumb",
    shopDescription: "Unisex clothing and accessories for testing the full Starlier buying flow.",
    shopNow: "Shop Now",
    shopStockSummary: "In stock · {count} styles",
    size: "Size",
    sizeQuantity: "Size {size} / Qty {quantity}",
    sizeFit: "Size & fit",
    sizeFitDescription: "Select your usual size for a regular fit, or size up for a more relaxed campaign silhouette.",
    sizeGuide: "Size guide",
    terms: "Terms",
    switchToEnglish: "Switch to English",
    switchToVietnamese: "Switch to Tiếng Việt",
    streetAddress: "Street address",
    apartmentLandmark: "Apartment, suite, landmark",
    subtotal: "Subtotal",
    summary: "Summary",
    total: "Total",
    order: "Order",
    orderSummary: "Order summary",
    checkout: "Checkout",
    checkoutDescription: "Enter delivery details, drop a location pin, then generate your SePay QR.",
    checkoutEmpty: "Your checkout is empty.",
    checkoutFailed: "Checkout could not be completed. Please try again.",
    unavailableVariant: "This item is no longer available in the selected size or quantity.",
    city: "City",
    quantityFor: "Quantity for {product}",
    locationBrowserUnavailable: "Browser location is not available.",
    locationFinding: "Finding your location...",
    locationAdded: "Location added.",
    locationPermissionDenied: "Location permission was denied.",
    locationPositionUnavailable: "Your location could not be determined.",
    locationTimedOut: "Location request timed out.",
    locationPinFallback: "You can still click the map to drop a pin.",
    googleMapsActive: "Google Maps is active for delivery pins.",
    googleMapsUnavailable: "Google Maps could not load. Check NEXT_PUBLIC_GOOGLE_MAPS_API_KEY.",
    googleEmailNotVerified: "Google did not return a verified email address.",
    googleNotConfigured: "Google sign-in is not configured yet.",
    googleProfileFailed: "Google profile information could not be loaded.",
    googleSignInFailed: "Google sign-in could not be completed.",
    googleStateExpired: "Google sign-in expired. Please try again.",
    googleTokenExchange: "Google sign-in could not exchange the authorization code.",
    guestOrderHistoryDescription: "Search guest orders using the same email and phone from checkout.",
    guestOrders: "Guest orders",
    openMap: "Open map",
    mapLoadsAfterClick: "{provider} will load after this click.",
    openStreetMapActive: "Using OpenStreetMap. Add NEXT_PUBLIC_GOOGLE_MAPS_API_KEY to enable Google Maps.",
    useMyLocation: "Use my location",
    longitude: "Longitude",
    name: "Name",
    noFavorites: "No favorites yet.",
    noOrdersMatched: "No orders matched that email and phone.",
    openDeliveryPin: "Open delivery pin",
    orderConfirmation: "Order confirmation",
    orderHistory: "Order history",
    orderLookupFailed: "Could not find orders with those details.",
    orderTrackingDescription: "We created the order and are tracking payment status through the provider callback.",
    orders: "Orders",
    password: "Password",
    phoneUsedAtCheckout: "Phone used at checkout",
    searchOrders: "Search orders",
    searchingOrders: "Searching...",
    shippingAddress: "Shipping",
    signIn: "Sign in",
    signOut: "Sign out",
    signedInOrdersEmpty: "Orders placed while signed in will appear here.",
    starlierAccount: "Starlier account",
    status: "Status",
    statusCanceled: "Canceled",
    statusCreated: "Created",
    statusFailed: "Failed",
    statusFulfilled: "Fulfilled",
    statusFulfilling: "Fulfilling",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusPendingPayment: "Pending payment",
    statusUnknown: "Status unavailable",
    alreadyHaveAccount: "Already have an account",
    createAccount: "Create account",
    incorrectCredentials: "Email or password is incorrect.",
    invalidSignup: "Use a valid email and a password of at least 6 characters.",
    items: "Items",
    viewAll: "View all",
    waitingPayment: "Waiting for payment confirmation...",
    yourOrderHistory: "Your order history",
    inStock: "In stock",
    viewCampaign: "View Campaign"
  },
  vi: {
    account: "Tài khoản",
    accountExists: "Email này đã có tài khoản. Hãy đăng nhập.",
    accountPrompt: "Đăng nhập để lưu sản phẩm yêu thích và xem đơn hàng.",
    accountNumber: "Số tài khoản",
    addFavorite: "Thêm {product} vào mục yêu thích",
    addToCart: "Thêm vào giỏ",
    addedToCart: "Đã thêm {product} vào giỏ",
    all: "Tất cả",
    bags: "Túi",
    bank: "Ngân hàng",
    buyNow: "Mua ngay",
    buyNowCheckout: "Thanh toán mua ngay",
    calculatedAtCheckout: "Tính tại bước thanh toán",
    campaign: "Chiến dịch",
    campaignTitle: "Đồng phục sau nửa đêm",
    care: "Bảo quản",
    careDescription: "Giặt nhẹ bằng nước lạnh, phơi phẳng và tránh nhiệt trực tiếp để bảo vệ bề mặt sản phẩm.",
    cart: "Giỏ hàng",
    cartEmpty: "Giỏ hàng của bạn đang trống.",
    cartEmptyDescription: "Thêm sản phẩm từ cửa hàng để tiếp tục thanh toán.",
    cartItemCount: "{count} sản phẩm",
    cartItemCountPlural: "{count} sản phẩm",
    cartWithCount: "Giỏ hàng, {count} sản phẩm",
    categoryBags: "Túi",
    categoryShirt: "Sơ mi",
    categoryShorts: "Quần short",
    categoryTshirt: "Áo thun",
    closeSearch: "Đóng tìm kiếm",
    close: "Đóng",
    closePaymentNotification: "Đóng thông báo thanh toán",
    collectionNotes: "Ghi chú bộ sưu tập",
    contact: "Liên hệ",
    continueShopping: "Tiếp tục mua sắm",
    continueWithGoogle: "Tiếp tục với Google",
    country: "Quốc gia",
    creatingPayment: "Đang tạo thanh toán...",
    customerCare: "Chăm sóc khách hàng",
    delivery: "Giao hàng",
    details: "Chi tiết",
    deliveryAddress: "Địa chỉ giao hàng",
    deliveryLocation: "Vị trí giao hàng",
    deliveryNote: "Ghi chú giao hàng",
    deliveryPin: "Ghim vị trí giao hàng",
    deliveryPinDescription: "Chạm vào bản đồ hoặc dùng vị trí hiện tại của bạn.",
    discover: "Khám phá",
    discoverBagsAlt: "Túi tote Starlier được mang trong phố đêm",
    discoverShirtsAlt: "Áo sơ mi Starlier trong không gian nội thất",
    emptyProducts: "Chưa có sản phẩm nào được hiển thị.",
    enterShop: "Vào cửa hàng",
    estimatedShipping: "Phí giao hàng dự kiến",
    exchangeReturns: "Đổi trả",
    exploreCategory: "Khám phá {category}",
    firstSignal: "First Signal",
    fit: "Phom dáng",
    fitDescription: "Phom rộng vừa phải với vai gọn, lớp áo lửng và đường nét tiện dụng.",
    fitStructured: "Phom unisex có cấu trúc",
    fullName: "Họ và tên",
    footerContact: "Liên hệ",
    footerEmail: "care@starlier.com",
    footerHours: "Thứ 2-Thứ 7, 10:00-19:00",
    footerLocation: "Hà Nội, Việt Nam",
    footerNote: "Những phom dáng streetwear lặng và sắc, dành cho tín hiệu đầu tiên sau nửa đêm.",
    footerPolicies: "Chính sách",
    footerSocial: "Mạng xã hội",
    footerTagline: "Thời trang unisex điện ảnh từ Hà Nội.",
    email: "Email",
    emailUsedAtCheckout: "Email dùng khi thanh toán",
    favorites: "Yêu thích",
    findGuestOrders: "Tìm đơn hàng khách",
    findOrderHistory: "Tìm lịch sử đơn hàng",
    languageEnglish: "English",
    languageVietnamese: "Tiếng Việt",
    itemCount: "{count} sản phẩm",
    latitude: "Vĩ độ",
    latestRelease: "Phát hành mới nhất",
    material: "Chất liệu",
    materialDescription: "Poplin, mesh và fleece nén được cân bằng cho trang phục hằng ngày sắc gọn.",
    memo: "Nội dung chuyển khoản",
    newArrival: "Sản phẩm mới",
    noCheckoutItems: "Không tìm thấy sản phẩm thanh toán. Hãy thêm lại sản phẩm trước khi thanh toán.",
    newsletter: "Bản tin",
    newsletterCopy: "Nhận thông tin drop mới, restock và campaign riêng.",
    paymentSecurity: "Thanh toán an toàn",
    palette: "Bảng màu",
    paletteDescription: "Trắng giấy, đen mực, xám sương và những tín hiệu xanh lạnh nhỏ.",
    payByQr: "Thanh toán bằng QR",
    payment: "Thanh toán",
    paymentConfirmed: "Đã xác nhận thanh toán",
    paymentResultDescription: "Thanh toán của bạn đang được xác nhận. Starlier sẽ cập nhật đơn hàng từ nhà cung cấp thanh toán.",
    paymentStatus: "Trạng thái thanh toán",
    paymentSuccessDescription: "Đơn hàng của bạn đã được xác nhận. Starlier sẽ chuẩn bị đơn và liên hệ khi cần.",
    paymentSuccessful: "Thanh toán thành công",
    lowStock: "Sắp hết hàng: còn {count}",
    pieceAvailable: "Còn 1 sản phẩm",
    piecesAvailable: "Còn {count} sản phẩm",
    soldOut: "Hết hàng",
    phone: "Số điện thoại",
    postalCode: "Mã bưu chính",
    province: "Tỉnh / thành",
    privacy: "Bảo mật",
    primaryNavigation: "Điều hướng chính",
    productCategories: "Danh mục sản phẩm",
    productDetails: "Thông tin dịch vụ sản phẩm",
    productFromCollection: "{category} thuộc {collection}, hoàn thiện gọn gàng cho trang phục hằng ngày.",
    productGallery: "Hình ảnh {product}",
    qrAlt: "Mã QR SePay cho đơn {orderNumber}",
    qrExpired: "QR đã hết hiệu lực",
    qrExpiredDescription: "Tạo lại đơn hàng để nhận mã QR mới trước khi chuyển khoản.",
    qrExpiredTitle: "Mã QR đã hết hiệu lực sau 5 phút.",
    qrRemaining: "Còn {time}",
    qrValidFor: "QR còn hiệu lực {time}",
    recentlyViewed: "ĐÃ XEM GẦN ĐÂY",
    removeFavorite: "Xóa {product} khỏi mục yêu thích",
    removeRecentlyViewed: "Xóa sản phẩm đã xem gần đây",
    remove: "XÓA",
    resultCount: "{count} kết quả",
    returns: "Đổi trả",
    returnToShop: "Quay lại cửa hàng",
    scanToPay: "Quét mã để thanh toán",
    search: "Tìm kiếm",
    searchDialog: "Tìm sản phẩm",
    searchEmpty: "Chưa có kết quả chính xác. Hãy thử tên sản phẩm, danh mục, bộ sưu tập hoặc chất liệu.",
    searchPlaceholder: "Nhập từ khóa tìm kiếm",
    searchResults: "KẾT QUẢ TÌM KIẾM",
    searchTrends: "XU HƯỚNG TÌM KIẾM",
    searching: "Đang tìm...",
    sepayInstruction: "Giữ nguyên số tiền và nội dung chuyển khoản để SePay tự động xác nhận thanh toán.",
    shirts: "Sơ mi",
    shipping: "Phí ship",
    shippingAtCheckout: "Giao hàng toàn quốc, xác nhận tại bước thanh toán",
    shippingReturns: "Giao hàng & đổi trả",
    shippingReturnsDescription: "Đơn hàng được chuẩn bị sau khi xác nhận thanh toán. Hỗ trợ đổi trả với sản phẩm chưa qua sử dụng.",
    shop: "Tất cả sản phẩm",
    shopAll: "Xem tất cả",
    shopBreadcrumb: "Điều hướng cửa hàng",
    shopDescription: "Quần áo và phụ kiện unisex cho trải nghiệm mua hàng Starlier.",
    shopNow: "Mua ngay",
    shopStockSummary: "Còn hàng · {count} mẫu",
    size: "Kích cỡ",
    sizeQuantity: "Size {size} / SL {quantity}",
    sizeFit: "Kích cỡ & phom",
    sizeFitDescription: "Chọn size thường mặc cho phom tiêu chuẩn, hoặc tăng một size để có phom campaign rộng hơn.",
    sizeGuide: "Bảng size",
    terms: "Điều khoản",
    switchToEnglish: "Switch to English",
    switchToVietnamese: "Switch to Tiếng Việt",
    streetAddress: "Địa chỉ",
    apartmentLandmark: "Căn hộ, tòa nhà, địa điểm nhận biết",
    subtotal: "Tạm tính",
    summary: "Tóm tắt",
    total: "Tổng cộng",
    order: "Đơn hàng",
    orderSummary: "Tóm tắt đơn hàng",
    checkout: "Thanh toán",
    checkoutDescription: "Nhập thông tin giao hàng, ghim vị trí rồi tạo mã QR SePay.",
    checkoutEmpty: "Đơn thanh toán của bạn đang trống.",
    checkoutFailed: "Không thể hoàn tất thanh toán. Vui lòng thử lại.",
    unavailableVariant: "Sản phẩm không còn đủ số lượng hoặc kích cỡ đã chọn.",
    city: "Thành phố",
    quantityFor: "Số lượng của {product}",
    locationBrowserUnavailable: "Trình duyệt không hỗ trợ truy cập vị trí.",
    locationFinding: "Đang tìm vị trí của bạn...",
    locationAdded: "Đã thêm vị trí.",
    locationPermissionDenied: "Bạn chưa cấp quyền truy cập vị trí.",
    locationPositionUnavailable: "Không thể xác định vị trí của bạn.",
    locationTimedOut: "Yêu cầu vị trí đã hết thời gian.",
    locationPinFallback: "Bạn vẫn có thể chạm vào bản đồ để ghim vị trí.",
    googleMapsActive: "Google Maps đang được dùng để ghim vị trí giao hàng.",
    googleMapsUnavailable: "Không thể tải Google Maps. Hãy kiểm tra NEXT_PUBLIC_GOOGLE_MAPS_API_KEY.",
    googleEmailNotVerified: "Google không trả về địa chỉ email đã xác minh.",
    googleNotConfigured: "Đăng nhập Google chưa được cấu hình.",
    googleProfileFailed: "Không thể tải thông tin hồ sơ Google.",
    googleSignInFailed: "Không thể hoàn tất đăng nhập Google.",
    googleStateExpired: "Phiên đăng nhập Google đã hết hạn. Vui lòng thử lại.",
    googleTokenExchange: "Không thể đổi mã xác thực đăng nhập Google.",
    guestOrderHistoryDescription: "Tìm đơn khách bằng email và số điện thoại đã dùng khi thanh toán.",
    guestOrders: "Đơn hàng khách",
    openMap: "Mở bản đồ",
    mapLoadsAfterClick: "{provider} sẽ tải sau khi bạn bấm.",
    openStreetMapActive: "Đang dùng OpenStreetMap. Thêm NEXT_PUBLIC_GOOGLE_MAPS_API_KEY để bật Google Maps.",
    useMyLocation: "Dùng vị trí của tôi",
    longitude: "Kinh độ",
    name: "Chủ tài khoản",
    noFavorites: "Chưa có sản phẩm yêu thích.",
    noOrdersMatched: "Không có đơn hàng khớp với email và số điện thoại này.",
    openDeliveryPin: "Mở vị trí giao hàng",
    orderConfirmation: "Xác nhận đơn hàng",
    orderHistory: "Lịch sử đơn hàng",
    orderLookupFailed: "Không thể tìm đơn hàng với thông tin này.",
    orderTrackingDescription: "Đơn hàng đã được tạo và trạng thái thanh toán đang được theo dõi tự động.",
    orders: "Đơn hàng",
    password: "Mật khẩu",
    phoneUsedAtCheckout: "Số điện thoại dùng khi thanh toán",
    searchOrders: "Tìm đơn hàng",
    searchingOrders: "Đang tìm...",
    shippingAddress: "Giao hàng",
    signIn: "Đăng nhập",
    signOut: "Đăng xuất",
    signedInOrdersEmpty: "Các đơn đặt khi đăng nhập sẽ xuất hiện tại đây.",
    starlierAccount: "Tài khoản Starlier",
    status: "Trạng thái",
    statusCanceled: "Đã hủy",
    statusCreated: "Đã tạo",
    statusFailed: "Thất bại",
    statusFulfilled: "Đã hoàn tất",
    statusFulfilling: "Đang chuẩn bị",
    statusPaid: "Đã thanh toán",
    statusPending: "Đang chờ",
    statusPendingPayment: "Chờ thanh toán",
    statusUnknown: "Chưa có trạng thái",
    alreadyHaveAccount: "Đã có tài khoản",
    createAccount: "Tạo tài khoản",
    incorrectCredentials: "Email hoặc mật khẩu không đúng.",
    invalidSignup: "Hãy dùng email hợp lệ và mật khẩu có ít nhất 6 ký tự.",
    items: "Sản phẩm",
    viewAll: "Xem tất cả",
    waitingPayment: "Đang chờ xác nhận thanh toán...",
    yourOrderHistory: "Lịch sử đơn hàng của bạn",
    inStock: "Còn hàng",
    viewCampaign: "Xem chiến dịch"
  }
} as const;

export type TranslationKey = keyof typeof translations.en;

export function categoryTranslationKey(category: string): TranslationKey | null {
  const normalized = category.trim().toLowerCase();
  if (normalized === "t-shirt") return "categoryTshirt";
  if (normalized === "shirt") return "categoryShirt";
  if (normalized === "shorts") return "categoryShorts";
  if (normalized === "bags" || normalized === "accessories") return "categoryBags";
  return null;
}

export function statusTranslationKey(status: string): TranslationKey | null {
  const keys: Record<string, TranslationKey> = {
    CANCELED: "statusCanceled",
    CANCELLED: "statusCanceled",
    CREATED: "statusCreated",
    FAILED: "statusFailed",
    FULFILLED: "statusFulfilled",
    FULFILLING: "statusFulfilling",
    PAID: "statusPaid",
    PENDING: "statusPending",
    PENDING_PAYMENT: "statusPendingPayment"
  };

  return keys[status.toUpperCase()] ?? null;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

function isStorefrontLanguage(value: string | null): value is StorefrontLanguage {
  return value === "en" || value === "vi";
}

function interpolateTranslation(template: string, values?: TranslationValues) {
  if (!values) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  );
}

function getLanguageSnapshot(): StorefrontLanguage {
  const storedLanguage = window.localStorage.getItem(STORAGE_KEY);
  return isStorefrontLanguage(storedLanguage) ? storedLanguage : "en";
}

function subscribeToLanguage(onStoreChange: () => void) {
  const handleStorage = (event: StorageEvent) => {
    if (event.key === STORAGE_KEY) onStoreChange();
  };
  window.addEventListener("storage", handleStorage);
  window.addEventListener(LANGUAGE_CHANGE_EVENT, onStoreChange);

  return () => {
    window.removeEventListener("storage", handleStorage);
    window.removeEventListener(LANGUAGE_CHANGE_EVENT, onStoreChange);
  };
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const language = useSyncExternalStore(
    subscribeToLanguage,
    getLanguageSnapshot,
    (): StorefrontLanguage => "en"
  );

  const value = useMemo<LanguageContextValue>(() => {
    const setLanguage = (nextLanguage: StorefrontLanguage) => {
      window.localStorage.setItem(STORAGE_KEY, nextLanguage);
      document.documentElement.lang = nextLanguage;
      window.dispatchEvent(new Event(LANGUAGE_CHANGE_EVENT));
    };

    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage(language === "en" ? "vi" : "en"),
      t: (key, values) => interpolateTranslation(translations[language][key], values)
    };
  }, [language]);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
